{% set name = "pybinding" %}
{% set version = "0.9.5" %}
{% set sha256 = "a3b0fd5c7bc6babdd265797698573a2ffe31edc5c4c6c4265262aa6f1005603d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<36]
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.12
    - scipy >=0.19
    - matplotlib-base >=2.0
    - pytest >=5.0

test:
  imports:
    - pybinding

about:
  home: http://pybinding.site/
  license: BSD-2-Clause
  license_family: BSD
  license_file: license.md
  summary: 'Package for numerical tight-binding calculations in solid state physics'
  doc_url: http://docs.pybinding.site/
  dev_url: https://github.com/dean0x7d/pybinding

extra:
  recipe-maintainers:
    - dean0x7d
