travis:
  secure:
    BINSTAR_TOKEN: bEQriY/kRF5yKf/l5hz4xqfaXslfJuJ91TR2OUEfyrTFD6va7bz2fYLssXHMz1/7jhPbteoYednKhNHHOJNq+DIAeX8fBsDTJ7+HZGcn6SQl2FjZ9gvpZlrnwxYByKXRbQonZ4wzsNyCQPW+9qTpeyf9w6Y2PJ9DMT4mP5+W2NF2eVgMNEb8TNebQ86KJcXZsJ92GZ3N4DboSqSHxB1ROm88kd/5lwm71LhbISVdh3FckjHiUJRzsWAp2rKGbw8C9F2SXDTUzJBCj8tXn/vfCed34nudrCm8n0pdaXIfJyrjinixmcHBV0qF2AtuahAyIEtOey8QCrq6u6Qg//cFTGwC1mVJVWajHZ5T09Nxrkq+bpbXiaPl+3r3IT+lh79l/9NiVnkjCOW6blLiAa5Tv/eRwwtAM3T5c/t7RUU1n+UV9lKihQSkJb+VVEk1PY5xcHjhZIqszmsbAU5kwnejgsHTqZuiOWpMSiqdEtjpNwSMOJV12NJwwTzJM4Xzl0UVDTXnfe7uAiWU5PP9cbx6jK2BaL6AEmJWiTWX1vOSpFa8ZQR6uAk2jkA4Yomc0EHMBRD7HD7YG66meHFTxcQvPO72Yv5sgTGmKyjGe5MGXzExFjLBnKHLdAt6SkAyh9NIwmNT2tmK/XY1lJnq3y7hmaCcGK2uMLw9Ei6kBPWSY2E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
